name: Code formatting

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    # https://pypi.org/project/black/
    - name: Check code formatting
      run: |
        pip install black==21.5b2
        black --check .
